### ISSUE TITLE
Explanation of scope is confusing

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/intro-to-variables.js#15]
Towards the end, I think the explanation of scope is pretty jumbled.

Seems like we are jumping btwn points.

A point that is lost is that when you have a variable defined in a different scope, it is pointing to a different variable. Simple point, but seems to be lost in the current explanation.

**Comment by pletcher** [comment]
Thanks for the feedback. I tried to clarify a couple of things -- this README could definitely use some tweaking.

The main problem is that scope is _generally_ pretty wonky to get your head around the first time, but I'll be sure to circle back here in the future.
